<?php

/**
 * This is the model base class for the table "tipo_planilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoPlanilla".
 *
 * Columns in table "tipo_planilla" available as properties of the model,
 * followed by relations of table "tipo_planilla" available as properties of the model.
 *
 * @property integer $id_tipo_planilla
 * @property string $descripcion
 *
 * @property LocalizacionPlanilla[] $localizacionPlanillas
 * @property Planilla[] $planillas
 */
abstract class BaseTipoPlanilla extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_planilla';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoPlanilla|TipoPlanillas', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion', 'length', 'max'=>35),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_tipo_planilla, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'localizacionPlanillas' => array(self::HAS_MANY, 'LocalizacionPlanilla', 'id_tipo_planilla'),
			'planillas' => array(self::HAS_MANY, 'Planilla', 'id_tipo_planilla'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_tipo_planilla' => Yii::t('app', 'Id Tipo Planilla'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'localizacionPlanillas' => null,
			'planillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_tipo_planilla', $this->id_tipo_planilla);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}