<?php

/**
 * This is the model base class for the table "nivel_servicio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NivelServicio".
 *
 * Columns in table "nivel_servicio" available as properties of the model,
 * followed by relations of table "nivel_servicio" available as properties of the model.
 *
 * @property integer $id_nivel
 * @property string $descripcion
 * @property string $codigo
 *
 * @property SalaCicloAnio[] $salaCicloAnios
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseNivelServicio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'nivel_servicio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NivelServicio|NivelServicios', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion, codigo', 'required'),
			array('codigo', 'length', 'max'=>2),
			array('id_nivel, descripcion, codigo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'salaCicloAnios' => array(self::HAS_MANY, 'SalaCicloAnio', 'id_nivel'),
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_nivel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_nivel' => Yii::t('app', 'Id Nivel'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'codigo' => Yii::t('app', 'Codigo'),
			'salaCicloAnios' => null,
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_nivel', $this->id_nivel);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('codigo', $this->codigo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}