<?php

/**
 * This is the model base class for the table "localizacion_planilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "LocalizacionPlanilla".
 *
 * Columns in table "localizacion_planilla" available as properties of the model,
 * followed by relations of table "localizacion_planilla" available as properties of the model.
 *
 * @property integer $id_localizacion_planilla
 * @property integer $id_localizacion
 * @property integer $id_tipo_planilla
 * @property integer $id_establecimiento
 *
 * @property TipoPlanilla $idTipoPlanilla
 */
abstract class BaseLocalizacionPlanilla extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'localizacion_planilla';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'LocalizacionPlanilla|LocalizacionPlanillas', $n);
	}

	public static function representingColumn() {
		return 'id_localizacion_planilla';
	}

	public function rules() {
		return array(
			array('id_localizacion, id_tipo_planilla, id_establecimiento', 'numerical', 'integerOnly'=>true),
			array('id_localizacion, id_tipo_planilla, id_establecimiento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_localizacion_planilla, id_localizacion, id_tipo_planilla, id_establecimiento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTipoPlanilla' => array(self::BELONGS_TO, 'TipoPlanilla', 'id_tipo_planilla'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_localizacion_planilla' => Yii::t('app', 'Id Localizacion Planilla'),
			'id_localizacion' => Yii::t('app', 'Id Localizacion'),
			'id_tipo_planilla' => null,
			'id_establecimiento' => Yii::t('app', 'Id Establecimiento'),
			'idTipoPlanilla' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_localizacion_planilla', $this->id_localizacion_planilla);
		$criteria->compare('id_localizacion', $this->id_localizacion);
		$criteria->compare('id_tipo_planilla', $this->id_tipo_planilla);
		$criteria->compare('id_establecimiento', $this->id_establecimiento);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}