<?php

/**
 * This is the model base class for the table "hola".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Hola".
 *
 * Columns in table "hola" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_hola
 * @property string $desp
 *
 */
abstract class BaseHola extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'hola';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Hola|Holas', $n);
	}

	public static function representingColumn() {
		return 'desp';
	}

	public function rules() {
		return array(
			array('id_hola', 'required'),
			array('id_hola', 'numerical', 'integerOnly'=>true),
			array('desp', 'length', 'max'=>30),
			array('desp', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_hola, desp', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_hola' => Yii::t('app', 'Id Hola'),
			'desp' => Yii::t('app', 'Desp'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_hola', $this->id_hola);
		$criteria->compare('desp', $this->desp, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}