<?php

/**
 * This is the model base class for the table "turno".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Turno".
 *
 * Columns in table "turno" available as properties of the model,
 * followed by relations of table "turno" available as properties of the model.
 *
 * @property integer $id_turno
 * @property string $descripcion
 * @property string $codigo
 *
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseTurno extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'turno';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Turno|Turnos', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion, codigo', 'required'),
			array('codigo', 'length', 'max'=>2),
			array('id_turno, descripcion, codigo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_turno'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_turno' => Yii::t('app', 'Id Turno'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'codigo' => Yii::t('app', 'Codigo'),
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_turno', $this->id_turno);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('codigo', $this->codigo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}