<?php

/**
 * This is the model base class for the table "actividad_taller".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ActividadTaller".
 *
 * Columns in table "actividad_taller" available as properties of the model,
 * followed by relations of table "actividad_taller" available as properties of the model.
 *
 * @property string $descripcion
 * @property integer $id_actividad_taller
 *
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseActividadTaller extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'actividad_taller';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ActividadTaller|ActividadTallers', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion', 'required'),
			array('descripcion', 'length', 'max'=>20),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('descripcion, id_actividad_taller', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_actividad_taller'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'descripcion' => Yii::t('app', 'Descripcion'),
			'id_actividad_taller' => Yii::t('app', 'Id Actividad Taller'),
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('id_actividad_taller', $this->id_actividad_taller);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}