<?php

/**
 * This is the model base class for the table "sala_ciclo_anio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "SalaCicloAnio".
 *
 * Columns in table "sala_ciclo_anio" available as properties of the model,
 * followed by relations of table "sala_ciclo_anio" available as properties of the model.
 *
 * @property integer $id_sala_ciclo_anio
 * @property string $descripcion
 * @property string $codigo
 * @property integer $id_nivel
 *
 * @property NivelServicio $idNivel
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseSalaCicloAnio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'sala_ciclo_anio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'SalaCicloAnio|SalaCicloAnios', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('id_nivel', 'numerical', 'integerOnly'=>true),
			array('codigo', 'length', 'max'=>2),
			array('descripcion', 'safe'),
			array('descripcion, codigo, id_nivel', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_sala_ciclo_anio, descripcion, codigo, id_nivel', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idNivel' => array(self::BELONGS_TO, 'NivelServicio', 'id_nivel'),
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_sala_ciclo_anio'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_sala_ciclo_anio' => Yii::t('app', 'Id Sala Ciclo Anio'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'codigo' => Yii::t('app', 'Codigo'),
			'id_nivel' => null,
			'idNivel' => null,
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_sala_ciclo_anio', $this->id_sala_ciclo_anio);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('id_nivel', $this->id_nivel);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}