<?php

/**
 * This is the model base class for the table "caracter_actividad".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "CaracterActividad".
 *
 * Columns in table "caracter_actividad" available as properties of the model,
 * followed by relations of table "caracter_actividad" available as properties of the model.
 *
 * @property integer $id_caracter_actividad
 * @property string $descripcion
 *
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseCaracterActividad extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'caracter_actividad';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'CaracterActividad|CaracterActividads', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion', 'safe'),
			array('descripcion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_caracter_actividad, descripcion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_caracter_actividad'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_caracter_actividad' => Yii::t('app', 'Id Caracter Actividad'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_caracter_actividad', $this->id_caracter_actividad);
		$criteria->compare('descripcion', $this->descripcion, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}