<?php

/**
 * This is the model base class for the table "titulo_tipo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TituloTipo".
 *
 * Columns in table "titulo_tipo" available as properties of the model,
 * followed by relations of table "titulo_tipo" available as properties of the model.
 *
 * @property integer $c_titulo
 * @property integer $c_carrera
 * @property integer $c_nivel_titulo
 * @property string $descripcion
 * @property integer $cod_rama
 * @property integer $cod_disciplina
 * @property integer $cod_carrera
 * @property integer $cod_titulo
 * @property string $descripcion_ampliada
 * @property integer $c_denominacion
 *
 * @property DetallePlanilla[] $detallePlanillas
 * @property TituloOfertaTipo[] $tituloOfertaTipos
 */
abstract class BaseTituloTipo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'titulo_tipo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TituloTipo|TituloTipos', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('c_titulo, c_carrera', 'required'),
			array('c_titulo, c_carrera, c_nivel_titulo, cod_rama, cod_disciplina, cod_carrera, cod_titulo, c_denominacion', 'numerical', 'integerOnly'=>true),
			array('descripcion, descripcion_ampliada', 'safe'),
			array('c_nivel_titulo, descripcion, cod_rama, cod_disciplina, cod_carrera, cod_titulo, descripcion_ampliada, c_denominacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('c_titulo, c_carrera, c_nivel_titulo, descripcion, cod_rama, cod_disciplina, cod_carrera, cod_titulo, descripcion_ampliada, c_denominacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_titulo'),
			'tituloOfertaTipos' => array(self::HAS_MANY, 'TituloOfertaTipo', 'c_titulo'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'c_titulo' => Yii::t('app', 'C Titulo'),
			'c_carrera' => Yii::t('app', 'C Carrera'),
			'c_nivel_titulo' => Yii::t('app', 'C Nivel Titulo'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'cod_rama' => Yii::t('app', 'Cod Rama'),
			'cod_disciplina' => Yii::t('app', 'Cod Disciplina'),
			'cod_carrera' => Yii::t('app', 'Cod Carrera'),
			'cod_titulo' => Yii::t('app', 'Cod Titulo'),
			'descripcion_ampliada' => Yii::t('app', 'Descripcion Ampliada'),
			'c_denominacion' => Yii::t('app', 'C Denominacion'),
			'detallePlanillas' => null,
			'tituloOfertaTipos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('c_titulo', $this->c_titulo);
		$criteria->compare('c_carrera', $this->c_carrera);
		$criteria->compare('c_nivel_titulo', $this->c_nivel_titulo);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('cod_rama', $this->cod_rama);
		$criteria->compare('cod_disciplina', $this->cod_disciplina);
		$criteria->compare('cod_carrera', $this->cod_carrera);
		$criteria->compare('cod_titulo', $this->cod_titulo);
		$criteria->compare('descripcion_ampliada', $this->descripcion_ampliada, true);
		$criteria->compare('c_denominacion', $this->c_denominacion);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function SelectPlanDeEstudio()
	{
		/* echo "<PRE>";
			print_r($_POST);
		echo "</PRE>"; */
		$id_localizacion= Yii::app()->getSession()->get('id_localizacion');
		
	
	
		$sql = "Select distinct
    titulo_tipo.c_titulo,
    titulo_tipo.descripcion
    From
    oferta_local Inner Join
    oferta_tipo On oferta_local.c_oferta = oferta_tipo.c_oferta Inner Join
    localizacion On oferta_local.id_localizacion = localizacion.id_localizacion
    Inner Join
    establecimiento On localizacion.id_establecimiento =
    establecimiento.id_establecimiento Inner Join
    estado_tipo On oferta_local.c_estado = estado_tipo.c_estado And
    localizacion.c_estado = estado_tipo.c_estado And establecimiento.c_estado =
    estado_tipo.c_estado Inner Join
    titulo_oferta_tipo On titulo_oferta_tipo.c_oferta = oferta_tipo.c_oferta
    Inner Join
    titulo_tipo On titulo_oferta_tipo.c_titulo = titulo_tipo.c_titulo Inner Join
    plan_estudio_local On plan_estudio_local.id_oferta_local =
    oferta_local.id_oferta_local And plan_estudio_local.c_titulo_oferta =
    titulo_oferta_tipo.c_titulo_oferta Inner Join
    plan_estudio_local_secundaria
    On plan_estudio_local_secundaria.id_plan_estudio_local =
    plan_estudio_local.id_plan_estudio_local Inner Join
    orientacion_tipo On plan_estudio_local_secundaria.c_orientacion =
    orientacion_tipo.c_orientacion
    Where
	localizacion.id_localizacion = '$id_localizacion' And
	oferta_local.c_estado = 1 And
    plan_estudio_local.c_requisito <> 2";
	
		$connection = Yii::app()->db;
		$command = $connection->createCommand($sql);
		$lista = $command->queryAll();
		
		return $lista;	
		//localizacion.id_localizacion = '$id_localizacion' And
		
		}
}