<?php

/**
 * This is the model base class for the table "educacion_adulto".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "EducacionAdulto".
 *
 * Columns in table "educacion_adulto" available as properties of the model,
 * followed by relations of table "educacion_adulto" available as properties of the model.
 *
 * @property integer $id_educacion_adulto
 * @property integer $id_localizacion
 * @property integer $id_ciclo_anio
 * @property integer $id_nivel
 * @property integer $id_turno
 * @property integer $id_seccion
 * @property integer $id_modalidad
 * @property integer $total_alumnos
 * @property integer $total_varones
 * @property integer $total_mujeres
 * @property integer $total_asistencia_media
 * @property integer $total_sec_div_mul
 * @property integer $total_sec_div_ind
 * @property integer $total_alf_ind
 * @property integer $total_alf_mul
 * @property integer $total_pri_ind
 * @property integer $total_pri_mul
 * @property integer $total_sec_ind
 * @property integer $total_sec_mul
 * @property integer $total_egb_ind
 * @property integer $total_egb_mul
 * @property integer $total_pol_ind
 * @property integer $total_pol_mul
 * @property integer $id_establecimiento
 *
 * @property Seccion $idSeccion
 * @property NivelServicio $idNivel
 * @property Turno $idTurno
 * @property CicloAnio $idCicloAnio
 * @property Establecimiento $idEstablecimiento
 */
abstract class BaseEducacionAdulto extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'educacion_adulto';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'EducacionAdulto|EducacionAdultos', $n);
	}

	public static function representingColumn() {
		return 'id_educacion_adulto';
	}

	public function rules() {
		return array(
			array('id_educacion_adulto', 'required'),
			array('id_educacion_adulto, id_localizacion, id_ciclo_anio, id_nivel, id_turno, id_seccion, id_modalidad, total_alumnos, total_varones, total_mujeres, total_asistencia_media, total_sec_div_mul, total_sec_div_ind, total_alf_ind, total_alf_mul, total_pri_ind, total_pri_mul, total_sec_ind, total_sec_mul, total_egb_ind, total_egb_mul, total_pol_ind, total_pol_mul, id_establecimiento', 'numerical', 'integerOnly'=>true),
			array('id_localizacion, id_ciclo_anio, id_nivel, id_turno, id_seccion, id_modalidad, total_alumnos, total_varones, total_mujeres, total_asistencia_media, total_sec_div_mul, total_sec_div_ind, total_alf_ind, total_alf_mul, total_pri_ind, total_pri_mul, total_sec_ind, total_sec_mul, total_egb_ind, total_egb_mul, total_pol_ind, total_pol_mul, id_establecimiento', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_educacion_adulto, id_localizacion, id_ciclo_anio, id_nivel, id_turno, id_seccion, id_modalidad, total_alumnos, total_varones, total_mujeres, total_asistencia_media, total_sec_div_mul, total_sec_div_ind, total_alf_ind, total_alf_mul, total_pri_ind, total_pri_mul, total_sec_ind, total_sec_mul, total_egb_ind, total_egb_mul, total_pol_ind, total_pol_mul, id_establecimiento', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idSeccion' => array(self::BELONGS_TO, 'Seccion', 'id_seccion'),
			'idNivel' => array(self::BELONGS_TO, 'NivelServicio', 'id_nivel'),
			'idTurno' => array(self::BELONGS_TO, 'Turno', 'id_turno'),
			'idCicloAnio' => array(self::BELONGS_TO, 'CicloAnio', 'id_ciclo_anio'),
			'idEstablecimiento' => array(self::BELONGS_TO, 'Establecimiento', 'id_establecimiento'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_educacion_adulto' => Yii::t('app', 'Id Educacion Adulto'),
			'id_localizacion' => Yii::t('app', 'Id Localizacion'),
			'id_ciclo_anio' => null,
			'id_nivel' => null,
			'id_turno' => null,
			'id_seccion' => null,
			'id_modalidad' => Yii::t('app', 'Id Modalidad'),
			'total_alumnos' => Yii::t('app', 'Total Alumnos'),
			'total_varones' => Yii::t('app', 'Total Varones'),
			'total_mujeres' => Yii::t('app', 'Total Mujeres'),
			'total_asistencia_media' => Yii::t('app', 'Total Asistencia Media'),
			'total_sec_div_mul' => Yii::t('app', 'Total Sec Div Mul'),
			'total_sec_div_ind' => Yii::t('app', 'Total Sec Div Ind'),
			'total_alf_ind' => Yii::t('app', 'Total Alf Ind'),
			'total_alf_mul' => Yii::t('app', 'Total Alf Mul'),
			'total_pri_ind' => Yii::t('app', 'Total Pri Ind'),
			'total_pri_mul' => Yii::t('app', 'Total Pri Mul'),
			'total_sec_ind' => Yii::t('app', 'Total Sec Ind'),
			'total_sec_mul' => Yii::t('app', 'Total Sec Mul'),
			'total_egb_ind' => Yii::t('app', 'Total Egb Ind'),
			'total_egb_mul' => Yii::t('app', 'Total Egb Mul'),
			'total_pol_ind' => Yii::t('app', 'Total Pol Ind'),
			'total_pol_mul' => Yii::t('app', 'Total Pol Mul'),
			'id_establecimiento' => null,
			'idSeccion' => null,
			'idNivel' => null,
			'idTurno' => null,
			'idCicloAnio' => null,
			'idEstablecimiento' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_educacion_adulto', $this->id_educacion_adulto);
		$criteria->compare('id_localizacion', $this->id_localizacion);
		$criteria->compare('id_ciclo_anio', $this->id_ciclo_anio);
		$criteria->compare('id_nivel', $this->id_nivel);
		$criteria->compare('id_turno', $this->id_turno);
		$criteria->compare('id_seccion', $this->id_seccion);
		$criteria->compare('id_modalidad', $this->id_modalidad);
		$criteria->compare('total_alumnos', $this->total_alumnos);
		$criteria->compare('total_varones', $this->total_varones);
		$criteria->compare('total_mujeres', $this->total_mujeres);
		$criteria->compare('total_asistencia_media', $this->total_asistencia_media);
		$criteria->compare('total_sec_div_mul', $this->total_sec_div_mul);
		$criteria->compare('total_sec_div_ind', $this->total_sec_div_ind);
		$criteria->compare('total_alf_ind', $this->total_alf_ind);
		$criteria->compare('total_alf_mul', $this->total_alf_mul);
		$criteria->compare('total_pri_ind', $this->total_pri_ind);
		$criteria->compare('total_pri_mul', $this->total_pri_mul);
		$criteria->compare('total_sec_ind', $this->total_sec_ind);
		$criteria->compare('total_sec_mul', $this->total_sec_mul);
		$criteria->compare('total_egb_ind', $this->total_egb_ind);
		$criteria->compare('total_egb_mul', $this->total_egb_mul);
		$criteria->compare('total_pol_ind', $this->total_pol_ind);
		$criteria->compare('total_pol_mul', $this->total_pol_mul);
		$criteria->compare('id_establecimiento', $this->id_establecimiento);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}