<?php

/**
 * This is the model base class for the table "responsable".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Responsable".
 *
 * Columns in table "responsable" available as properties of the model,
 * followed by relations of table "responsable" available as properties of the model.
 *
 * @property integer $id_responsable
 * @property string $apellido
 * @property string $telefono
 * @property integer $nro_documento
 * @property integer $c_tipo_documento
 * @property string $email
 * @property string $fecha_actualizacion
 * @property string $fecha_nacimiento
 * @property integer $c_nacionalidad
 * @property string $cuil_cuit
 * @property integer $c_sexo
 * @property string $nombre
 *
 * @property Establecimiento[] $establecimientos
 */
abstract class BaseResponsable extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'responsable';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Responsable|Responsables', $n);
	}

	public static function representingColumn() {
		return 'apellido';
	}

	public function rules() {
		return array(
			array('apellido, fecha_actualizacion', 'required'),
			array('nro_documento, c_tipo_documento, c_nacionalidad, c_sexo', 'numerical', 'integerOnly'=>true),
			array('cuil_cuit', 'length', 'max'=>13),
			array('telefono, email, fecha_nacimiento, nombre', 'safe'),
			array('telefono, nro_documento, c_tipo_documento, email, fecha_nacimiento, c_nacionalidad, cuil_cuit, c_sexo, nombre', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_responsable, apellido, telefono, nro_documento, c_tipo_documento, email, fecha_actualizacion, fecha_nacimiento, c_nacionalidad, cuil_cuit, c_sexo, nombre', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'establecimientos' => array(self::HAS_MANY, 'Establecimiento', 'id_responsable'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_responsable' => Yii::t('app', 'Id Responsable'),
			'apellido' => Yii::t('app', 'Responsable'),
			'telefono' => Yii::t('app', 'Telefono'),
			'nro_documento' => Yii::t('app', 'Nro Documento'),
			'c_tipo_documento' => Yii::t('app', 'C Tipo Documento'),
			'email' => Yii::t('app', 'Email'),
			'fecha_actualizacion' => Yii::t('app', 'Fecha Actualizacion'),
			'fecha_nacimiento' => Yii::t('app', 'Fecha Nacimiento'),
			'c_nacionalidad' => Yii::t('app', 'C Nacionalidad'),
			'cuil_cuit' => Yii::t('app', 'Cuil Cuit'),
			'c_sexo' => Yii::t('app', 'C Sexo'),
			'nombre' => Yii::t('app', 'Nombre'),
			'establecimientos' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_responsable', $this->id_responsable);
		$criteria->compare('apellido', $this->apellido, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('nro_documento', $this->nro_documento);
		$criteria->compare('c_tipo_documento', $this->c_tipo_documento);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('fecha_actualizacion', $this->fecha_actualizacion, true);
		$criteria->compare('fecha_nacimiento', $this->fecha_nacimiento, true);
		$criteria->compare('c_nacionalidad', $this->c_nacionalidad);
		$criteria->compare('cuil_cuit', $this->cuil_cuit, true);
		$criteria->compare('c_sexo', $this->c_sexo);
		$criteria->compare('nombre', $this->nombre, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	function getApellidoNombre()
	{
		return $this->apellido.', '.$this->nombre;
	}
}