<?php

/**
 * This is the model base class for the table "orientacion".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Orientacion".
 *
 * Columns in table "orientacion" available as properties of the model,
 * followed by relations of table "orientacion" available as properties of the model.
 *
 * @property integer $id_orientacion
 * @property string $descripcion
 * @property string $codigo
 * @property integer $id_tipo_orientacion
 *
 * @property TipoOrientacion $idTipoOrientacion
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseOrientacion extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'orientacion';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Orientacion|Orientacions', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion, codigo', 'required'),
			array('id_tipo_orientacion', 'numerical', 'integerOnly'=>true),
			array('codigo', 'length', 'max'=>2),
			array('id_tipo_orientacion', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_orientacion, descripcion, codigo, id_tipo_orientacion', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'idTipoOrientacion' => array(self::BELONGS_TO, 'TipoOrientacion', 'id_tipo_orientacion'),
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_orientacion'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_orientacion' => Yii::t('app', 'Id Orientacion'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'codigo' => Yii::t('app', 'Codigo'),
			'id_tipo_orientacion' => null,
			'idTipoOrientacion' => null,
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_orientacion', $this->id_orientacion);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('codigo', $this->codigo, true);
		$criteria->compare('id_tipo_orientacion', $this->id_tipo_orientacion);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}