<?php

/**
 * This is the model base class for the table "nivel_servicio".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NivelServicio".
 *
 * Columns in table "nivel_servicio" available as properties of the model,
 * followed by relations of table "nivel_servicio" available as properties of the model.
 *
 * @property integer $id_nivel
 * @property string $descripcion
 * @property string $codigo
 *
 * @property SalaCicloAnio[] $salaCicloAnios
 * @property DetallePlanilla[] $detallePlanillas
 */
abstract class BaseNivelServicio extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'nivel_servicio';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NivelServicio|NivelServicios', $n);
	}

	public static function representingColumn() {
		return 'descripcion';
	}

	public function rules() {
		return array(
			array('descripcion, codigo', 'required'),
			array('codigo', 'length', 'max'=>2),
			array('id_nivel, descripcion, codigo', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'salaCicloAnios' => array(self::HAS_MANY, 'SalaCicloAnio', 'id_nivel'),
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_nivel'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_nivel' => Yii::t('app', 'Id Nivel'),
			'descripcion' => Yii::t('app', 'Descripcion'),
			'codigo' => Yii::t('app', 'Codigo'),
			'salaCicloAnios' => null,
			'detallePlanillas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_nivel', $this->id_nivel);
		$criteria->compare('descripcion', $this->descripcion, true);
		$criteria->compare('codigo', $this->codigo, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function SelectNivel()
	{
		$id_localizacion= Yii::app()->getSession()->get('id_localizacion');
	
	
		$sql = "Select
		orientacion_tipo.c_orientacion,
		orientacion_tipo.descripcion
		From
		oferta_local Inner Join
		oferta_tipo On oferta_local.c_oferta = oferta_tipo.c_oferta Inner Join
		localizacion On oferta_local.id_localizacion = localizacion.id_localizacion
		Inner Join
		establecimiento On localizacion.id_establecimiento =
		establecimiento.id_establecimiento Inner Join
		estado_tipo On oferta_local.c_estado = estado_tipo.c_estado And
		localizacion.c_estado = estado_tipo.c_estado And establecimiento.c_estado =
		estado_tipo.c_estado Inner Join
		titulo_oferta_tipo On titulo_oferta_tipo.c_oferta = oferta_tipo.c_oferta
		Inner Join
		titulo_tipo On titulo_oferta_tipo.c_titulo = titulo_tipo.c_titulo Inner Join
		plan_estudio_local On plan_estudio_local.id_oferta_local =
		oferta_local.id_oferta_local And plan_estudio_local.c_titulo_oferta =
		titulo_oferta_tipo.c_titulo_oferta Inner Join
		plan_estudio_local_secundaria
		On plan_estudio_local_secundaria.id_plan_estudio_local =
		plan_estudio_local.id_plan_estudio_local Inner Join
		orientacion_tipo On plan_estudio_local_secundaria.c_orientacion =
		orientacion_tipo.c_orientacion
		Where
		localizacion.id_localizacion = '$id_localizacion' And
		oferta_local.c_estado = 1 And
		plan_estudio_local.c_requisito <> 2 ";
	
		$connection = Yii::app()->db;
		$command = $connection->createCommand($sql);
		$lista = $command->queryAll();
		return $lista;
	
	}
}