<?php

/**
 * This is the model base class for the table "planilla".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Planilla".
 *
 * Columns in table "planilla" available as properties of the model,
 * followed by relations of table "planilla" available as properties of the model.
 *
 * @property integer $id_planilla
 * @property string $mes
 * @property integer $anio
 * @property integer $id_tipo_planilla
 * @property integer $id_establecimiento
 * @property string $ingresador
 * @property integer $alu_tot_ind
 * @property integer $tot_ind_alf
 * @property integer $tot_ind_pri
 * @property integer $tot_ind_sec
 * @property integer $alu_tot_mul
 * @property integer $tot_mul_alf
 * @property integer $tot_mul_pri
 * @property integer $tot_mul_sec
 * @property integer $alu_mul_ind
 * @property integer $alu_tot_alf
 * @property integer $alu_tot_pri
 * @property integer $alu_tot_sec
 * @property string $fecha_creado
 * @property string $ultimo_login
 * @property integer $tot_ind_pol
 * @property integer $tot_mul_pol
 * @property integer $alu_tot_pol
 * @property integer $confirmado
 * @property integer $tot_alu_act
 * @property integer $tot_act_var
 * @property integer $tot_act_muj
 * @property integer $alu_obl_tot
 * @property integer $alu_obl_var
 * @property integer $alu_obl_muj
 * @property integer $alu_opt_tot
 * @property integer $alu_opt_var
 * @property integer $alu_opt_muj
 * @property integer $id_localizacion
 * @property integer $tot_ind_jam
 * @property integer $tot_ind_jif
 * @property integer $tot_mul_jmx
 * @property integer $tot_alm_ben
 * @property integer $tot_mul_imx
 * @property integer $tot_cop_man
 * @property integer $tot_cop_tar
 * @property integer $tot_ref_man
 * @property integer $tot_ref_tar
 * @property integer $tot_ind_egb
 * @property integer $tot_mul_eex
 * @property integer $tot_sec_div
 * @property integer $tot_mul_sex
 * @property integer $tot_mul_pex
 * @property string $dom_act
 * @property string $telefono
 * @property integer $tot_mul_jix
 * @property DetallePlanilla[] $detallePlanillas
 * @property TipoPlanilla $idTipoPlanilla
 * @property Establecimiento $idEstablecimiento
 * @property Localizacion $idLocalizacion
 * @property string  $otr_ser_ali
 * @property integer $tot_otr_ser
 * @property integer $ser_ali_esp
 * */
abstract class BasePlanilla extends GxActiveRecord {

	public $detalle;
	
	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'planilla';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Planilla|Planillas', $n);
	}

	public static function representingColumn() {
		return 'mes';
	}

	public function rules() {
		return array(
			array('anio, id_tipo_planilla, id_establecimiento, alu_tot_ind, tot_ind_alf, tot_ind_pri, tot_ind_sec, alu_tot_mul, tot_mul_alf, tot_mul_pri, tot_mul_sec, alu_mul_ind, alu_tot_alf, alu_tot_pri, alu_tot_sec, tot_ind_pol, tot_mul_pol, alu_tot_pol, confirmado, tot_alu_act, tot_act_var, tot_act_muj, alu_obl_tot, alu_obl_var, alu_obl_muj, alu_opt_tot, alu_opt_var, alu_opt_muj, id_localizacion, tot_ind_jam, tot_ind_jif, tot_mul_jmx, tot_alm_ben, tot_mul_imx, tot_cop_man, tot_cop_tar, tot_ref_man, tot_ref_tar, tot_ind_egb, tot_mul_eex, tot_sec_div, tot_mul_sex, tot_mul_pex,tot_mul_jix ,otr_ser_ali, tot_otr_ser', 'numerical', 'integerOnly'=>true),
			array('mes', 'length', 'max'=>10),
			array('ingresador', 'length', 'max'=>30),
			array('fecha_creado, ultimo_login, dom_act, telefono, ser_ali_esp', 'safe'),
			array('mes, anio, id_tipo_planilla, id_establecimiento, ingresador, alu_tot_ind, tot_ind_alf, tot_ind_pri, tot_ind_sec, alu_tot_mul, tot_mul_alf, tot_mul_pri, tot_mul_sec, alu_mul_ind, alu_tot_alf, alu_tot_pri, alu_tot_sec, fecha_creado, ultimo_login, tot_ind_pol, tot_mul_pol, alu_tot_pol, confirmado, tot_alu_act, tot_act_var, tot_act_muj, alu_obl_tot, alu_obl_var, alu_obl_muj, alu_opt_tot, alu_opt_var, alu_opt_muj, id_localizacion, fecha_creado, ultimo_login, tot_ind_jam, tot_ind_jif, tot_mul_jmx, tot_alm_ben, tot_mul_imx, tot_cop_man, tot_cop_tar, tot_ref_man, tot_ref_tar, tot_ind_egb, tot_mul_eex, tot_sec_div, tot_mul_sex, tot_mul_pex, dom_act, telefono, tot_mul_jix, otr_ser_ali, tot_otr_ser', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_planilla, mes, anio, id_tipo_planilla, id_establecimiento, ingresador, alu_tot_ind, tot_ind_alf, tot_ind_pri, tot_ind_sec, alu_tot_mul, tot_mul_alf, tot_mul_pri, tot_mul_sec, alu_mul_ind, alu_tot_alf, alu_tot_pri, alu_tot_sec, fecha_creado, ultimo_login, tot_ind_pol, tot_mul_pol, alu_tot_pol, confirmado, tot_alu_act, tot_act_var, tot_act_muj, alu_obl_tot, alu_obl_var, alu_obl_muj, alu_opt_tot, alu_opt_var, alu_opt_muj, id_localizacion, fecha_creado, ultimo_login, tot_ind_jam, tot_ind_jif, tot_mul_jmx, tot_alm_ben, tot_mul_imx, tot_cop_man, tot_cop_tar, tot_ref_man, tot_ref_tar, tot_ind_egb, tot_mul_eex, tot_sec_div, tot_mul_sex, tot_mul_pex, dom_act, telefono, tot_mul_jix, otr_ser_ali, tot_otr_ser', 'safe', 'on'=>'search'),
			
			array('id_tipo_planilla, id_establecimiento, ingresador, alu_tot_mul, alu_tot_ind,tot_ind_alf,tot_ind_pri,alu_mul_ind,tot_mul_alf,tot_mul_pri,alu_tot_alf,alu_tot_alf,alu_tot_pri,tot_alm_ben,tot_cop_man,tot_ref_man,tot_ref_tar,dom_act,telefono', 'required', 'on'=>'adultoprimaria'),
			
			array('id_tipo_planilla, id_establecimiento, ingresador, tot_ind_sec, tot_mul_sex, tot_sec_div, tot_alm_ben,tot_cop_man,tot_ref_man,tot_ref_tar,dom_act,telefono', 'required', 'on'=>'adultosecundaria'),
			array('id_tipo_planilla, id_establecimiento, ingresador,tot_ind_jam,tot_ind_jif,tot_mul_jmx,tot_mul_jix,tot_mul_imx,tot_sec_div,tot_alm_ben,tot_cop_man,tot_cop_tar,tot_ref_man,tot_ref_tar,dom_act,telefono,otr_ser_ali', 'required', 'on'=>'inicial'),
			array('id_tipo_planilla, id_establecimiento, ingresador, tot_alu_act, tot_act_var, tot_act_muj, alu_obl_tot, alu_obl_var, alu_obl_muj, alu_opt_tot, alu_opt_var, alu_opt_muj', 'required', 'on'=>'noformal'),
			array('id_tipo_planilla, id_establecimiento, ingresador, tot_alu_act, tot_act_var, tot_act_muj, alu_obl_tot, alu_obl_var, alu_obl_muj, alu_opt_tot, alu_opt_var, alu_opt_muj', 'required', 'on'=>'serviciocomplementario'),
			array('id_tipo_planilla, id_establecimiento, ingresador', 'required', 'on'=>'ttp'),
			array('id_tipo_planilla, id_establecimiento, ingresador', 'required', 'on'=>'itinerario'),
			array('id_tipo_planilla, id_establecimiento, ingresador,tot_sec_div,tot_alm_ben,tot_cop_man,tot_cop_tar,tot_ref_man,tot_ref_tar,dom_act,telefono,otr_ser_ali', 'required', 'on'=>'secundaria'),
				
			array('id_tipo_planilla, id_establecimiento, ingresador,tot_ind_egb,tot_mul_eex,tot_sec_div,tot_alm_ben,tot_cop_man,tot_cop_tar,tot_ref_man,tot_ref_tar,dom_act,telefono,otr_ser_ali', 'required', 'on'=>'egb'),
				
		);
	}

	public function relations() {
		return array(
			'detallePlanillas' => array(self::HAS_MANY, 'DetallePlanilla', 'id_planilla'),
			'idTipoPlanilla' => array(self::BELONGS_TO, 'TipoPlanilla', 'id_tipo_planilla'),
			'idEstablecimiento' => array(self::BELONGS_TO, 'Establecimiento', 'id_establecimiento'),
			'idLocalizacion' => array(self::BELONGS_TO, 'Localizacion', 'id_localizacion'),
				
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_planilla' => Yii::t('app', 'Id Planilla'),
			'mes' => Yii::t('app', 'Mes'),
			'anio' => Yii::t('app', 'Año'),
			'id_tipo_planilla' => null,
			'id_establecimiento' =>  Yii::t('app', 'Establecimiento'),
			'ingresador' => Yii::t('app', 'Ingresador'),
			'alu_tot_ind' => Yii::t('app', 'Alu Tot Ind'),
			'tot_ind_alf' => Yii::t('app', 'Tot Ind Alf'),
			'tot_ind_pri' => Yii::t('app', 'Tot Ind Pri'),
			'tot_ind_sec' => Yii::t('app', 'Tot Ind Sec'),
			'alu_tot_mul' => Yii::t('app', 'Alu Tot Mul'),
			'tot_mul_alf' => Yii::t('app', 'Tot Mul Alf'),
			'tot_mul_pri' => Yii::t('app', 'Tot Mul Pri'),
			'tot_mul_sec' => Yii::t('app', 'Tot Mul Sec'),
			'alu_mul_ind' => Yii::t('app', 'Alu Mul Ind'),
			'alu_tot_alf' => Yii::t('app', 'Alu Tot Alf'),
			'alu_tot_pri' => Yii::t('app', 'Alu Tot Pri'),
			'alu_tot_sec' => Yii::t('app', 'Alu Tot Sec'),
			'fecha_creado' => Yii::t('app', 'Fecha Creado'),
			'ultimo_login' => Yii::t('app', 'Ultimo Login'),
			'tot_ind_pol' => Yii::t('app', 'Tot Ind Pol'),
			'tot_mul_pol' => Yii::t('app', 'Tot Mul Pol'),
			'alu_tot_pol' => Yii::t('app', 'Alu Tot Pol'),
			'confirmado' => Yii::t('app', 'Confirmado'),
			'tot_alu_act' => Yii::t('app', 'Tot Alu Act'),
			'tot_act_var' => Yii::t('app', 'Tot Act Var'),
			'tot_act_muj' => Yii::t('app', 'Tot Act Muj'),
			'alu_obl_tot' => Yii::t('app', 'Alu Obl Tot'),
			'alu_obl_var' => Yii::t('app', 'Alu Obl Var'),
			'alu_obl_muj' => Yii::t('app', 'Alu Obl Muj'),
			'alu_opt_tot' => Yii::t('app', 'Alu Opt Tot'),
			'alu_opt_var' => Yii::t('app', 'Alu Opt Var'),
			'alu_opt_muj' => Yii::t('app', 'Alu Opt Muj'),
			'id_localizacion' => Yii::t('app', 'Id Localizacion'),
			'fecha_creado' => Yii::t('app', 'Fecha Creado'),
			'ultimo_login' => Yii::t('app', 'Ultimo Login'),
			'tot_ind_jam' => Yii::t('app', 'Tot Ind Jam'),
			'tot_ind_jif' => Yii::t('app', 'Tot Ind Jif'),
			'tot_mul_jmx' => Yii::t('app', 'Tot Mul Jmx'),
			'tot_alm_ben' => Yii::t('app', 'Tot Alm Ben'),
			'tot_mul_imx' => Yii::t('app', 'Tot Mul Imx'),
			'tot_cop_man' => Yii::t('app', 'Tot Cop Man'),
			'tot_cop_tar' => Yii::t('app', 'Tot Cop Tar'),
			'tot_ref_man' => Yii::t('app', 'Tot Ref Man'),
			'tot_ref_tar' => Yii::t('app', 'Tot Ref Tar'),
			'tot_ind_egb' => Yii::t('app', 'Tot Ind Egb'),
			'tot_mul_eex' => Yii::t('app', 'Tot Mul Eex'),
			'tot_sec_div' => Yii::t('app', 'Tot Sec Div'),
			'tot_mul_sex' => Yii::t('app', 'Tot Mul Sex'),
			'tot_mul_pex' => Yii::t('app', 'Tot Mul Pex'),
			'dom_act' => Yii::t('app', 'Domicilio Actualizado'),
			'telefono' => Yii::t('app', 'Telefono/s'),
			'otr_ser_ali' => Yii::t('app', 'Otr Ser Ali'),
			'detallePlanillas' => null,
			'idTipoPlanilla' => null,
			'idEstablecimiento' =>  Yii::t('app', 'Establecimiento'),
			'idLocalizacion' => Yii::t('app', 'Localizacion'),
			'tot_mul_jix' => Yii::t('app', 'Tot Mul Jix'),
			'tot_otr_ser' => Yii::t('app', 'Tot Otr Ser'),
			'ser_ali_esp' => Yii::t('app', 'Ser Ali Esp'),
				
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_planilla', $this->id_planilla);
		$criteria->compare('mes', $this->mes, true);
		$criteria->compare('anio', $this->anio);
		$criteria->compare('id_tipo_planilla', $this->id_tipo_planilla);
		$criteria->compare('id_establecimiento', $this->id_establecimiento);
		$criteria->compare('ingresador', $this->ingresador, true);
		$criteria->compare('alu_tot_ind', $this->alu_tot_ind);
		$criteria->compare('tot_ind_alf', $this->tot_ind_alf);
		$criteria->compare('tot_ind_pri', $this->tot_ind_pri);
		$criteria->compare('tot_ind_sec', $this->tot_ind_sec);
		$criteria->compare('alu_tot_mul', $this->alu_tot_mul);
		$criteria->compare('tot_mul_alf', $this->tot_mul_alf);
		$criteria->compare('tot_mul_pri', $this->tot_mul_pri);
		$criteria->compare('tot_mul_sec', $this->tot_mul_sec);
		$criteria->compare('alu_mul_ind', $this->alu_mul_ind);
		$criteria->compare('alu_tot_alf', $this->alu_tot_alf);
		$criteria->compare('alu_tot_pri', $this->alu_tot_pri);
		$criteria->compare('alu_tot_sec', $this->alu_tot_sec);
		$criteria->compare('fecha_creado', $this->fecha_creado, true);
		$criteria->compare('ultimo_login', $this->ultimo_login, true);
		$criteria->compare('tot_ind_pol', $this->tot_ind_pol);
		$criteria->compare('tot_mul_pol', $this->tot_mul_pol);
		$criteria->compare('alu_tot_pol', $this->alu_tot_pol);
		$criteria->compare('confirmado', $this->confirmado);
		$criteria->compare('tot_alu_act', $this->tot_alu_act);
		$criteria->compare('tot_act_var', $this->tot_act_var);
		$criteria->compare('tot_act_muj', $this->tot_act_muj);
		$criteria->compare('alu_obl_tot', $this->alu_obl_tot);
		$criteria->compare('alu_obl_var', $this->alu_obl_var);
		$criteria->compare('alu_obl_muj', $this->alu_obl_muj);
		$criteria->compare('alu_opt_tot', $this->alu_opt_tot);
		$criteria->compare('alu_opt_var', $this->alu_opt_var);
		$criteria->compare('alu_opt_muj', $this->alu_opt_muj);
		$criteria->compare('id_localizacion', $this->id_localizacion);
		$criteria->compare('tot_ind_jam', $this->tot_ind_jam);
		$criteria->compare('tot_ind_jif', $this->tot_ind_jif);
		$criteria->compare('tot_mul_jmx', $this->tot_mul_jmx);
		$criteria->compare('tot_alm_ben', $this->tot_alm_ben);
		$criteria->compare('tot_mul_imx', $this->tot_mul_imx);
		$criteria->compare('tot_cop_man', $this->tot_cop_man);
		$criteria->compare('tot_cop_tar', $this->tot_cop_tar);
		$criteria->compare('tot_ref_man', $this->tot_ref_man);
		$criteria->compare('tot_ref_tar', $this->tot_ref_tar);
		$criteria->compare('tot_ind_egb', $this->tot_ind_egb);
		$criteria->compare('tot_mul_eex', $this->tot_mul_eex);
		$criteria->compare('tot_sec_div', $this->tot_sec_div);
		$criteria->compare('tot_mul_sex', $this->tot_mul_sex);
		$criteria->compare('tot_mul_pex', $this->tot_mul_pex);
		$criteria->compare('dom_act', $this->dom_act, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('tot_mul_jix', $this->tot_mul_jix);
		$criteria->compare('otr_ser_ali', $this->otr_ser_ali);
		$criteria->compare('tot_otr_ser', $this->tot_otr_ser);
		$criteria->compare('ser_ali_esp', $this->ser_ali_esp, true);
		
		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
	
	public function getGridDataProvider() {
	
		$criteria = new CDbCriteria;
	
		$criteria->compare('id_establecimiento', Yii::app()->getSession()->get('id_establecimiento'));
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder' => 'id_planilla',
				),
				'pagination' => array(
						'pagesize' => 30,
				),
		));
	
	}
	
	public function getGridDataProviderEst() {
	
		$criteria = new CDbCriteria;
		$criteria->select = 'mes,anio,id_establecimiento';
        $criteria->group = 'id_establecimiento,mes, anio';		
        return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				/*'sort'=>array(
						'defaultOrder' => 'id_planilla',
				),*/
				'pagination' => array(
						'pagesize' => 30,
				),
		));
	
	}
	
	public function getGridDataProviderLoc($id) {
	
		//$localizaciones = Planilla::model()->find('id_establecimiento = :id_uno',array(':id_uno'=>$id));
		//$establecimiento = Establecimiento::model()->find('id_establecimiento = :id_uno',array(':id_uno'=>$establecimientousuario->id_establecimiento));
	
		$criteria = new CDbCriteria;
	
		//$criteria->compare('id_planilla', $id);
		$criteria->compare('id_establecimiento', $id);
	
		return new CActiveDataProvider($this, array(
				'criteria' => $criteria,
				'sort'=>array(
						'defaultOrder' => 'id_localizacion',
				),
				'pagination' => array(
						'pagesize' => 30,
				),
		));
	
	}

	public static function getOnoffs()
	{
		return array(
				array('id'=>'1', 'title'=>'Si'),
				array('id'=>'0', 'title'=>'No'),
		);
	}
	public static function getOnoff($onoff)
	{
		if($onoff == 1)
			return 'Si';
		else
			return 'No';
	}
	
	public function getMesActivo(){
		return array("marzo" => "Marzo");
	}
	
	public function getAnioActivo(){
		return array("2013" => "2013");
	}
	
	public function getMesActivoString(){
		return 'Marzo';
	}
	
	
	public function getAnioActivoInteger(){
		return 2013;
	}
}