<?php

/**
 * This is the model base class for the table "datosest".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Datosest".
 *
 * Columns in table "datosest" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $id_datos_est
 * @property integer $id_planilla
 * @property integer $tot_dic_cla
 * @property integer $tot_dic_tit
 * @property integer $tot_dic_int
 * @property integer $tot_dic_tra
 * @property integer $tot_dic_sup
 * @property integer $tot_dic_sin
 * @property integer $tot_dic_pas
 * @property integer $tot_dic_com
 * @property integer $tot_dic_lic
 * @property integer $tot_dic_con
 * @property integer $tot_jar_mat
 * @property integer $tot_mat_tit
 * @property integer $tot_mat_int
 * @property integer $tot_mat_tra
 * @property integer $tot_mat_sup
 * @property integer $tot_mat_sin
 * @property integer $tot_mat_pas
 * @property integer $tot_mat_com
 * @property integer $tot_mat_lic
 * @property integer $tot_mat_con
 * @property integer $tot_jar_inf
 * @property integer $tot_inf_tit
 * @property integer $tot_inf_int
 * @property integer $tot_inf_tra
 * @property integer $tot_inf_sup
 * @property integer $tot_inf_sin
 * @property integer $tot_inf_pas
 * @property integer $tot_inf_com
 * @property integer $tot_inf_lic
 * @property integer $tot_inf_con
 * @property integer $tot_hor_egb
 * @property integer $tot_egb_tit
 * @property integer $tot_egb_int
 * @property integer $tot_egb_tra
 * @property integer $tot_egb_sup
 * @property integer $tot_egb_sin
 * @property integer $tot_egb_pas
 * @property integer $tot_egb_com
 * @property integer $tot_egb_lic
 * @property integer $tot_egb_con
 * @property integer $tot_hor_sec
 * @property integer $tot_sec_tit
 * @property integer $tot_sec_int
 * @property integer $tot_sec_tra
 * @property integer $tot_sec_sup
 * @property integer $tot_sec_sin
 * @property integer $tot_sec_pas
 * @property integer $tot_sec_com
 * @property integer $tot_sec_lic
 * @property integer $tot_sec_con
 * @property integer $tot_hor_pol
 * @property integer $tot_pol_tit
 * @property integer $tot_pol_int
 * @property integer $tot_pol_tra
 * @property integer $tot_pol_sup
 * @property integer $tot_pol_sin
 * @property integer $tot_pol_pas
 * @property integer $tot_pol_com
 * @property integer $tot_pol_lic
 * @property integer $tot_pol_con
 * @property integer $tot_act_fun
 * @property integer $tot_fun_tit
 * @property integer $tot_fun_int
 * @property integer $tot_fun_tra
 * @property integer $tot_fun_sup
 * @property integer $tot_fun_sin
 * @property integer $tot_fun_pas
 * @property integer $tot_fun_com
 * @property integer $tot_fun_lic
 * @property integer $tot_fun_con
 * @property integer $tot_hor_ins
 * @property integer $tot_ins_tit
 * @property integer $tot_ins_int
 * @property integer $tot_ins_tra
 * @property integer $tot_ins_sup
 * @property integer $tot_ins_sin
 * @property integer $tot_ins_pas
 * @property integer $tot_ins_com
 * @property integer $tot_ins_lic
 * @property integer $tot_ins_con
 * @property integer $tot_per_adm
 * @property integer $tot_adm_var
 * @property integer $tor_adm_muj
 * @property integer $tot_per_ser
 * @property integer $tot_ser_var
 * @property integer $tot_ser_muj
 * @property integer $tot_per_pla
 * @property integer $tot_pla_var
 * @property integer $tot_pla_muj
 * @property integer $tot_per_con
 * @property integer $tot_con_var
 * @property integer $tot_con_muj
 * @property integer $tot_per_nod
 * @property integer $tot_per_var
 * @property integer $tot_per_muj
 * @property integer $tot_doc_act
 * @property integer $tot_act_var
 * @property integer $tot_act_muj
 * @property integer $tot_per_pas
 * @property integer $tot_pas_var
 * @property integer $tot_pas_muj
 * @property integer $tot_doc_fun
 * @property integer $tot_doc_var
 * @property integer $tot_doc_muj
 * @property integer $tot_doc_otr
 * @property integer $tot_otr_var
 * @property integer $tot_otr_muj
 * @property string $dom_act
 * @property string $telefono
 * @property string $email
 * @property string $lugar_fecha
 * @property string $secretario
 * @property string $vicedirector
 * @property string $director
 * @property string $fec_ini_act
 * @property string $fec_ina
 * @property string $fec_ani
 * @property integer $tot_pol_tar
 * @property integer $tot_fun_tar
 * @property integer $tot_ins_tar
 *
 */
abstract class BaseDatosest extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'datosest';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Datosest|Datosests', $n);
	}

	public static function representingColumn() {
		return 'dom_act';
	}

	public function rules() {
		return array(
			array('id_datos_est', 'required'),
			array('id_datos_est, id_planilla, tot_dic_cla, tot_dic_tit, tot_dic_int, tot_dic_tra, tot_dic_sup, tot_dic_sin, tot_dic_pas, tot_dic_com, tot_dic_lic, tot_dic_con, tot_jar_mat, tot_mat_tit, tot_mat_int, tot_mat_tra, tot_mat_sup, tot_mat_sin, tot_mat_pas, tot_mat_com, tot_mat_lic, tot_mat_con, tot_jar_inf, tot_inf_tit, tot_inf_int, tot_inf_tra, tot_inf_sup, tot_inf_sin, tot_inf_pas, tot_inf_com, tot_inf_lic, tot_inf_con, tot_hor_egb, tot_egb_tit, tot_egb_int, tot_egb_tra, tot_egb_sup, tot_egb_sin, tot_egb_pas, tot_egb_com, tot_egb_lic, tot_egb_con, tot_hor_sec, tot_sec_tit, tot_sec_int, tot_sec_tra, tot_sec_sup, tot_sec_sin, tot_sec_pas, tot_sec_com, tot_sec_lic, tot_sec_con, tot_hor_pol, tot_pol_tit, tot_pol_int, tot_pol_tra, tot_pol_sup, tot_pol_sin, tot_pol_pas, tot_pol_com, tot_pol_lic, tot_pol_con, tot_act_fun, tot_fun_tit, tot_fun_int, tot_fun_tra, tot_fun_sup, tot_fun_sin, tot_fun_pas, tot_fun_com, tot_fun_lic, tot_fun_con, tot_hor_ins, tot_ins_tit, tot_ins_int, tot_ins_tra, tot_ins_sup, tot_ins_sin, tot_ins_pas, tot_ins_com, tot_ins_lic, tot_ins_con, tot_per_adm, tot_adm_var, tor_adm_muj, tot_per_ser, tot_ser_var, tot_ser_muj, tot_per_pla, tot_pla_var, tot_pla_muj, tot_per_con, tot_con_var, tot_con_muj, tot_per_nod, tot_per_var, tot_per_muj, tot_doc_act, tot_act_var, tot_act_muj, tot_per_pas, tot_pas_var, tot_pas_muj, tot_doc_fun, tot_doc_var, tot_doc_muj, tot_doc_otr, tot_otr_var, tot_otr_muj, tot_pol_tar, tot_fun_tar, tot_ins_tar', 'numerical', 'integerOnly'=>true),
			array('dom_act, telefono, email, lugar_fecha, secretario, vicedirector, director, fec_ini_act, fec_ina, fec_ani', 'safe'),
			array('id_planilla, tot_dic_cla, tot_dic_tit, tot_dic_int, tot_dic_tra, tot_dic_sup, tot_dic_sin, tot_dic_pas, tot_dic_com, tot_dic_lic, tot_dic_con, tot_jar_mat, tot_mat_tit, tot_mat_int, tot_mat_tra, tot_mat_sup, tot_mat_sin, tot_mat_pas, tot_mat_com, tot_mat_lic, tot_mat_con, tot_jar_inf, tot_inf_tit, tot_inf_int, tot_inf_tra, tot_inf_sup, tot_inf_sin, tot_inf_pas, tot_inf_com, tot_inf_lic, tot_inf_con, tot_hor_egb, tot_egb_tit, tot_egb_int, tot_egb_tra, tot_egb_sup, tot_egb_sin, tot_egb_pas, tot_egb_com, tot_egb_lic, tot_egb_con, tot_hor_sec, tot_sec_tit, tot_sec_int, tot_sec_tra, tot_sec_sup, tot_sec_sin, tot_sec_pas, tot_sec_com, tot_sec_lic, tot_sec_con, tot_hor_pol, tot_pol_tit, tot_pol_int, tot_pol_tra, tot_pol_sup, tot_pol_sin, tot_pol_pas, tot_pol_com, tot_pol_lic, tot_pol_con, tot_act_fun, tot_fun_tit, tot_fun_int, tot_fun_tra, tot_fun_sup, tot_fun_sin, tot_fun_pas, tot_fun_com, tot_fun_lic, tot_fun_con, tot_hor_ins, tot_ins_tit, tot_ins_int, tot_ins_tra, tot_ins_sup, tot_ins_sin, tot_ins_pas, tot_ins_com, tot_ins_lic, tot_ins_con, tot_per_adm, tot_adm_var, tor_adm_muj, tot_per_ser, tot_ser_var, tot_ser_muj, tot_per_pla, tot_pla_var, tot_pla_muj, tot_per_con, tot_con_var, tot_con_muj, tot_per_nod, tot_per_var, tot_per_muj, tot_doc_act, tot_act_var, tot_act_muj, tot_per_pas, tot_pas_var, tot_pas_muj, tot_doc_fun, tot_doc_var, tot_doc_muj, tot_doc_otr, tot_otr_var, tot_otr_muj, dom_act, telefono, email, lugar_fecha, secretario, vicedirector, director, fec_ini_act, fec_ina, fec_ani, tot_pol_tar, tot_fun_tar, tot_ins_tar', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id_datos_est, id_planilla, tot_dic_cla, tot_dic_tit, tot_dic_int, tot_dic_tra, tot_dic_sup, tot_dic_sin, tot_dic_pas, tot_dic_com, tot_dic_lic, tot_dic_con, tot_jar_mat, tot_mat_tit, tot_mat_int, tot_mat_tra, tot_mat_sup, tot_mat_sin, tot_mat_pas, tot_mat_com, tot_mat_lic, tot_mat_con, tot_jar_inf, tot_inf_tit, tot_inf_int, tot_inf_tra, tot_inf_sup, tot_inf_sin, tot_inf_pas, tot_inf_com, tot_inf_lic, tot_inf_con, tot_hor_egb, tot_egb_tit, tot_egb_int, tot_egb_tra, tot_egb_sup, tot_egb_sin, tot_egb_pas, tot_egb_com, tot_egb_lic, tot_egb_con, tot_hor_sec, tot_sec_tit, tot_sec_int, tot_sec_tra, tot_sec_sup, tot_sec_sin, tot_sec_pas, tot_sec_com, tot_sec_lic, tot_sec_con, tot_hor_pol, tot_pol_tit, tot_pol_int, tot_pol_tra, tot_pol_sup, tot_pol_sin, tot_pol_pas, tot_pol_com, tot_pol_lic, tot_pol_con, tot_act_fun, tot_fun_tit, tot_fun_int, tot_fun_tra, tot_fun_sup, tot_fun_sin, tot_fun_pas, tot_fun_com, tot_fun_lic, tot_fun_con, tot_hor_ins, tot_ins_tit, tot_ins_int, tot_ins_tra, tot_ins_sup, tot_ins_sin, tot_ins_pas, tot_ins_com, tot_ins_lic, tot_ins_con, tot_per_adm, tot_adm_var, tor_adm_muj, tot_per_ser, tot_ser_var, tot_ser_muj, tot_per_pla, tot_pla_var, tot_pla_muj, tot_per_con, tot_con_var, tot_con_muj, tot_per_nod, tot_per_var, tot_per_muj, tot_doc_act, tot_act_var, tot_act_muj, tot_per_pas, tot_pas_var, tot_pas_muj, tot_doc_fun, tot_doc_var, tot_doc_muj, tot_doc_otr, tot_otr_var, tot_otr_muj, dom_act, telefono, email, lugar_fecha, secretario, vicedirector, director, fec_ini_act, fec_ina, fec_ani, tot_pol_tar, tot_fun_tar, tot_ins_tar', 'safe', 'on'=>'search'),
			array('id_datos_est, id_planilla, tot_dic_cla, tot_dic_tit, tot_dic_int, tot_dic_tra, tot_dic_sup, tot_dic_sin, tot_dic_pas, tot_dic_com, tot_dic_lic, tot_dic_con, tot_jar_mat, tot_mat_tit, tot_mat_int, tot_mat_tra, tot_mat_sup, tot_mat_sin, tot_mat_pas, tot_mat_com, tot_mat_lic, tot_mat_con, tot_jar_inf, tot_inf_tit, tot_inf_int, tot_inf_tra, tot_inf_sup, tot_inf_sin, tot_inf_pas, tot_inf_com, tot_inf_lic, tot_inf_con, tot_hor_egb, tot_egb_tit, tot_egb_int, tot_egb_tra, tot_egb_sup, tot_egb_sin, tot_egb_pas, tot_egb_com, tot_egb_lic, tot_egb_con, tot_pol_pas, tot_act_fun, tot_fun_tit, tot_fun_int, tot_fun_tra, tot_fun_sup, tot_fun_sin, tot_fun_pas, tot_fun_com, tot_fun_lic, tot_fun_con, tot_hor_ins, tot_ins_tit, tot_ins_int, tot_ins_tra, tot_ins_sup, tot_ins_sin, tot_ins_pas, tot_ins_com, tot_ins_lic, tot_ins_con, tot_per_adm, tot_adm_var, tor_adm_muj, tot_per_ser, tot_ser_var, tot_ser_muj, tot_per_pla, tot_pla_var, tot_pla_muj, tot_per_con, tot_con_var, tot_con_muj, tot_per_nod, tot_per_var, tot_per_muj, tot_doc_act, tot_act_var, tot_act_muj, tot_per_pas, tot_pas_var, tot_pas_muj, tot_doc_fun, tot_doc_var, tot_doc_muj, tot_doc_otr, tot_otr_var, tot_otr_muj, dom_act, telefono, email, lugar_fecha, secretario, vicedirector, director, fec_ini_act, fec_ina, fec_ani, tot_fun_tar, tot_ins_tar', 'required','on'=>'jmjiegb'),
				);
	}
/*17900a5*/
	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id_datos_est' => Yii::t('app', 'Id Datos Est'),
			'id_planilla' => Yii::t('app', 'Id Planilla'),
			'tot_dic_cla' => Yii::t('app', 'Tot Dic Cla'),
			'tot_dic_tit' => Yii::t('app', 'Tot Dic Tit'),
			'tot_dic_int' => Yii::t('app', 'Tot Dic Int'),
			'tot_dic_tra' => Yii::t('app', 'Tot Dic Tra'),
			'tot_dic_sup' => Yii::t('app', 'Tot Dic Sup'),
			'tot_dic_sin' => Yii::t('app', 'Tot Dic Sin'),
			'tot_dic_pas' => Yii::t('app', 'Tot Dic Pas'),
			'tot_dic_com' => Yii::t('app', 'Tot Dic Com'),
			'tot_dic_lic' => Yii::t('app', 'Tot Dic Lic'),
			'tot_dic_con' => Yii::t('app', 'Tot Dic Con'),
			'tot_jar_mat' => Yii::t('app', 'Tot Jar Mat'),
			'tot_mat_tit' => Yii::t('app', 'Tot Mat Tit'),
			'tot_mat_int' => Yii::t('app', 'Tot Mat Int'),
			'tot_mat_tra' => Yii::t('app', 'Tot Mat Tra'),
			'tot_mat_sup' => Yii::t('app', 'Tot Mat Sup'),
			'tot_mat_sin' => Yii::t('app', 'Tot Mat Sin'),
			'tot_mat_pas' => Yii::t('app', 'Tot Mat Pas'),
			'tot_mat_com' => Yii::t('app', 'Tot Mat Com'),
			'tot_mat_lic' => Yii::t('app', 'Tot Mat Lic'),
			'tot_mat_con' => Yii::t('app', 'Tot Mat Con'),
			'tot_jar_inf' => Yii::t('app', 'Tot Jar Inf'),
			'tot_inf_tit' => Yii::t('app', 'Tot Inf Tit'),
			'tot_inf_int' => Yii::t('app', 'Tot Inf Int'),
			'tot_inf_tra' => Yii::t('app', 'Tot Inf Tra'),
			'tot_inf_sup' => Yii::t('app', 'Tot Inf Sup'),
			'tot_inf_sin' => Yii::t('app', 'Tot Inf Sin'),
			'tot_inf_pas' => Yii::t('app', 'Tot Inf Pas'),
			'tot_inf_com' => Yii::t('app', 'Tot Inf Com'),
			'tot_inf_lic' => Yii::t('app', 'Tot Inf Lic'),
			'tot_inf_con' => Yii::t('app', 'Tot Inf Con'),
			'tot_hor_egb' => Yii::t('app', 'Tot Hor Egb'),
			'tot_egb_tit' => Yii::t('app', 'Tot Egb Tit'),
			'tot_egb_int' => Yii::t('app', 'Tot Egb Int'),
			'tot_egb_tra' => Yii::t('app', 'Tot Egb Tra'),
			'tot_egb_sup' => Yii::t('app', 'Tot Egb Sup'),
			'tot_egb_sin' => Yii::t('app', 'Tot Egb Sin'),
			'tot_egb_pas' => Yii::t('app', 'Tot Egb Pas'),
			'tot_egb_com' => Yii::t('app', 'Tot Egb Com'),
			'tot_egb_lic' => Yii::t('app', 'Tot Egb Lic'),
			'tot_egb_con' => Yii::t('app', 'Tot Egb Con'),
			'tot_hor_sec' => Yii::t('app', 'Tot Hor Sec'),
			'tot_sec_tit' => Yii::t('app', 'Tot Sec Tit'),
			'tot_sec_int' => Yii::t('app', 'Tot Sec Int'),
			'tot_sec_tra' => Yii::t('app', 'Tot Sec Tra'),
			'tot_sec_sup' => Yii::t('app', 'Tot Sec Sup'),
			'tot_sec_sin' => Yii::t('app', 'Tot Sec Sin'),
			'tot_sec_pas' => Yii::t('app', 'Tot Sec Pas'),
			'tot_sec_com' => Yii::t('app', 'Tot Sec Com'),
			'tot_sec_lic' => Yii::t('app', 'Tot Sec Lic'),
			'tot_sec_con' => Yii::t('app', 'Tot Sec Con'),
			'tot_hor_pol' => Yii::t('app', 'Tot Hor Pol'),
			'tot_pol_tit' => Yii::t('app', 'Tot Pol Tit'),
			'tot_pol_int' => Yii::t('app', 'Tot Pol Int'),
			'tot_pol_tra' => Yii::t('app', 'Tot Pol Tra'),
			'tot_pol_sup' => Yii::t('app', 'Tot Pol Sup'),
			'tot_pol_sin' => Yii::t('app', 'Tot Pol Sin'),
			'tot_pol_pas' => Yii::t('app', 'Tot Pol Pas'),
			'tot_pol_com' => Yii::t('app', 'Tot Pol Com'),
			'tot_pol_lic' => Yii::t('app', 'Tot Pol Lic'),
			'tot_pol_con' => Yii::t('app', 'Tot Pol Con'),
			'tot_act_fun' => Yii::t('app', 'Tot Act Fun'),
			'tot_fun_tit' => Yii::t('app', 'Tot Fun Tit'),
			'tot_fun_int' => Yii::t('app', 'Tot Fun Int'),
			'tot_fun_tra' => Yii::t('app', 'Tot Fun Tra'),
			'tot_fun_sup' => Yii::t('app', 'Tot Fun Sup'),
			'tot_fun_sin' => Yii::t('app', 'Tot Fun Sin'),
			'tot_fun_pas' => Yii::t('app', 'Tot Fun Pas'),
			'tot_fun_com' => Yii::t('app', 'Tot Fun Com'),
			'tot_fun_lic' => Yii::t('app', 'Tot Fun Lic'),
			'tot_fun_con' => Yii::t('app', 'Tot Fun Con'),
			'tot_hor_ins' => Yii::t('app', 'Tot Hor Ins'),
			'tot_ins_tit' => Yii::t('app', 'Tot Ins Tit'),
			'tot_ins_int' => Yii::t('app', 'Tot Ins Int'),
			'tot_ins_tra' => Yii::t('app', 'Tot Ins Tra'),
			'tot_ins_sup' => Yii::t('app', 'Tot Ins Sup'),
			'tot_ins_sin' => Yii::t('app', 'Tot Ins Sin'),
			'tot_ins_pas' => Yii::t('app', 'Tot Ins Pas'),
			'tot_ins_com' => Yii::t('app', 'Tot Ins Com'),
			'tot_ins_lic' => Yii::t('app', 'Tot Ins Lic'),
			'tot_ins_con' => Yii::t('app', 'Tot Ins Con'),
			'tot_per_adm' => Yii::t('app', 'Tot Per Adm'),
			'tot_adm_var' => Yii::t('app', 'Tot Adm Var'),
			'tor_adm_muj' => Yii::t('app', 'Tor Adm Muj'),
			'tot_per_ser' => Yii::t('app', 'Tot Per Ser'),
			'tot_ser_var' => Yii::t('app', 'Tot Ser Var'),
			'tot_ser_muj' => Yii::t('app', 'Tot Ser Muj'),
			'tot_per_pla' => Yii::t('app', 'Tot Per Pla'),
			'tot_pla_var' => Yii::t('app', 'Tot Pla Var'),
			'tot_pla_muj' => Yii::t('app', 'Tot Pla Muj'),
			'tot_per_con' => Yii::t('app', 'Tot Per Con'),
			'tot_con_var' => Yii::t('app', 'Tot Con Var'),
			'tot_con_muj' => Yii::t('app', 'Tot Con Muj'),
			'tot_per_nod' => Yii::t('app', 'Tot Per Nod'),
			'tot_per_var' => Yii::t('app', 'Tot Per Var'),
			'tot_per_muj' => Yii::t('app', 'Tot Per Muj'),
			'tot_doc_act' => Yii::t('app', 'Tot Doc Act'),
			'tot_act_var' => Yii::t('app', 'Tot Act Var'),
			'tot_act_muj' => Yii::t('app', 'Tot Act Muj'),
			'tot_per_pas' => Yii::t('app', 'Tot Per Pas'),
			'tot_pas_var' => Yii::t('app', 'Tot Pas Var'),
			'tot_pas_muj' => Yii::t('app', 'Tot Pas Muj'),
			'tot_doc_fun' => Yii::t('app', 'Tot Doc Fun'),
			'tot_doc_var' => Yii::t('app', 'Tot Doc Var'),
			'tot_doc_muj' => Yii::t('app', 'Tot Doc Muj'),
			'tot_doc_otr' => Yii::t('app', 'Tot Doc Otr'),
			'tot_otr_var' => Yii::t('app', 'Tot Otr Var'),
			'tot_otr_muj' => Yii::t('app', 'Tot Otr Muj'),
			'dom_act' => Yii::t('app', 'Dom Act'),
			'telefono' => Yii::t('app', 'Telefono'),
			'email' => Yii::t('app', 'Email'),
			'lugar_fecha' => Yii::t('app', 'Lugar Fecha'),
			'secretario' => Yii::t('app', 'Secretario'),
			'vicedirector' => Yii::t('app', 'Vicedirector'),
			'director' => Yii::t('app', 'Director'),
			'fec_ini_act' => Yii::t('app', 'Fec Ini Act'),
			'fec_ina' => Yii::t('app', 'Fec Ina'),
			'fec_ani' => Yii::t('app', 'Fec Ani'),
			'tot_pol_tar' => Yii::t('app', 'Tot Pol Tar'),
			'tot_fun_tar' => Yii::t('app', 'Tot Fun Tar'),
			'tot_ins_tar' => Yii::t('app', 'Tot Ins Tar'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id_datos_est', $this->id_datos_est);
		$criteria->compare('id_planilla', $this->id_planilla);
		$criteria->compare('tot_dic_cla', $this->tot_dic_cla);
		$criteria->compare('tot_dic_tit', $this->tot_dic_tit);
		$criteria->compare('tot_dic_int', $this->tot_dic_int);
		$criteria->compare('tot_dic_tra', $this->tot_dic_tra);
		$criteria->compare('tot_dic_sup', $this->tot_dic_sup);
		$criteria->compare('tot_dic_sin', $this->tot_dic_sin);
		$criteria->compare('tot_dic_pas', $this->tot_dic_pas);
		$criteria->compare('tot_dic_com', $this->tot_dic_com);
		$criteria->compare('tot_dic_lic', $this->tot_dic_lic);
		$criteria->compare('tot_dic_con', $this->tot_dic_con);
		$criteria->compare('tot_jar_mat', $this->tot_jar_mat);
		$criteria->compare('tot_mat_tit', $this->tot_mat_tit);
		$criteria->compare('tot_mat_int', $this->tot_mat_int);
		$criteria->compare('tot_mat_tra', $this->tot_mat_tra);
		$criteria->compare('tot_mat_sup', $this->tot_mat_sup);
		$criteria->compare('tot_mat_sin', $this->tot_mat_sin);
		$criteria->compare('tot_mat_pas', $this->tot_mat_pas);
		$criteria->compare('tot_mat_com', $this->tot_mat_com);
		$criteria->compare('tot_mat_lic', $this->tot_mat_lic);
		$criteria->compare('tot_mat_con', $this->tot_mat_con);
		$criteria->compare('tot_jar_inf', $this->tot_jar_inf);
		$criteria->compare('tot_inf_tit', $this->tot_inf_tit);
		$criteria->compare('tot_inf_int', $this->tot_inf_int);
		$criteria->compare('tot_inf_tra', $this->tot_inf_tra);
		$criteria->compare('tot_inf_sup', $this->tot_inf_sup);
		$criteria->compare('tot_inf_sin', $this->tot_inf_sin);
		$criteria->compare('tot_inf_pas', $this->tot_inf_pas);
		$criteria->compare('tot_inf_com', $this->tot_inf_com);
		$criteria->compare('tot_inf_lic', $this->tot_inf_lic);
		$criteria->compare('tot_inf_con', $this->tot_inf_con);
		$criteria->compare('tot_hor_egb', $this->tot_hor_egb);
		$criteria->compare('tot_egb_tit', $this->tot_egb_tit);
		$criteria->compare('tot_egb_int', $this->tot_egb_int);
		$criteria->compare('tot_egb_tra', $this->tot_egb_tra);
		$criteria->compare('tot_egb_sup', $this->tot_egb_sup);
		$criteria->compare('tot_egb_sin', $this->tot_egb_sin);
		$criteria->compare('tot_egb_pas', $this->tot_egb_pas);
		$criteria->compare('tot_egb_com', $this->tot_egb_com);
		$criteria->compare('tot_egb_lic', $this->tot_egb_lic);
		$criteria->compare('tot_egb_con', $this->tot_egb_con);
		$criteria->compare('tot_hor_sec', $this->tot_hor_sec);
		$criteria->compare('tot_sec_tit', $this->tot_sec_tit);
		$criteria->compare('tot_sec_int', $this->tot_sec_int);
		$criteria->compare('tot_sec_tra', $this->tot_sec_tra);
		$criteria->compare('tot_sec_sup', $this->tot_sec_sup);
		$criteria->compare('tot_sec_sin', $this->tot_sec_sin);
		$criteria->compare('tot_sec_pas', $this->tot_sec_pas);
		$criteria->compare('tot_sec_com', $this->tot_sec_com);
		$criteria->compare('tot_sec_lic', $this->tot_sec_lic);
		$criteria->compare('tot_sec_con', $this->tot_sec_con);
		$criteria->compare('tot_hor_pol', $this->tot_hor_pol);
		$criteria->compare('tot_pol_tit', $this->tot_pol_tit);
		$criteria->compare('tot_pol_int', $this->tot_pol_int);
		$criteria->compare('tot_pol_tra', $this->tot_pol_tra);
		$criteria->compare('tot_pol_sup', $this->tot_pol_sup);
		$criteria->compare('tot_pol_sin', $this->tot_pol_sin);
		$criteria->compare('tot_pol_pas', $this->tot_pol_pas);
		$criteria->compare('tot_pol_com', $this->tot_pol_com);
		$criteria->compare('tot_pol_lic', $this->tot_pol_lic);
		$criteria->compare('tot_pol_con', $this->tot_pol_con);
		$criteria->compare('tot_act_fun', $this->tot_act_fun);
		$criteria->compare('tot_fun_tit', $this->tot_fun_tit);
		$criteria->compare('tot_fun_int', $this->tot_fun_int);
		$criteria->compare('tot_fun_tra', $this->tot_fun_tra);
		$criteria->compare('tot_fun_sup', $this->tot_fun_sup);
		$criteria->compare('tot_fun_sin', $this->tot_fun_sin);
		$criteria->compare('tot_fun_pas', $this->tot_fun_pas);
		$criteria->compare('tot_fun_com', $this->tot_fun_com);
		$criteria->compare('tot_fun_lic', $this->tot_fun_lic);
		$criteria->compare('tot_fun_con', $this->tot_fun_con);
		$criteria->compare('tot_hor_ins', $this->tot_hor_ins);
		$criteria->compare('tot_ins_tit', $this->tot_ins_tit);
		$criteria->compare('tot_ins_int', $this->tot_ins_int);
		$criteria->compare('tot_ins_tra', $this->tot_ins_tra);
		$criteria->compare('tot_ins_sup', $this->tot_ins_sup);
		$criteria->compare('tot_ins_sin', $this->tot_ins_sin);
		$criteria->compare('tot_ins_pas', $this->tot_ins_pas);
		$criteria->compare('tot_ins_com', $this->tot_ins_com);
		$criteria->compare('tot_ins_lic', $this->tot_ins_lic);
		$criteria->compare('tot_ins_con', $this->tot_ins_con);
		$criteria->compare('tot_per_adm', $this->tot_per_adm);
		$criteria->compare('tot_adm_var', $this->tot_adm_var);
		$criteria->compare('tor_adm_muj', $this->tor_adm_muj);
		$criteria->compare('tot_per_ser', $this->tot_per_ser);
		$criteria->compare('tot_ser_var', $this->tot_ser_var);
		$criteria->compare('tot_ser_muj', $this->tot_ser_muj);
		$criteria->compare('tot_per_pla', $this->tot_per_pla);
		$criteria->compare('tot_pla_var', $this->tot_pla_var);
		$criteria->compare('tot_pla_muj', $this->tot_pla_muj);
		$criteria->compare('tot_per_con', $this->tot_per_con);
		$criteria->compare('tot_con_var', $this->tot_con_var);
		$criteria->compare('tot_con_muj', $this->tot_con_muj);
		$criteria->compare('tot_per_nod', $this->tot_per_nod);
		$criteria->compare('tot_per_var', $this->tot_per_var);
		$criteria->compare('tot_per_muj', $this->tot_per_muj);
		$criteria->compare('tot_doc_act', $this->tot_doc_act);
		$criteria->compare('tot_act_var', $this->tot_act_var);
		$criteria->compare('tot_act_muj', $this->tot_act_muj);
		$criteria->compare('tot_per_pas', $this->tot_per_pas);
		$criteria->compare('tot_pas_var', $this->tot_pas_var);
		$criteria->compare('tot_pas_muj', $this->tot_pas_muj);
		$criteria->compare('tot_doc_fun', $this->tot_doc_fun);
		$criteria->compare('tot_doc_var', $this->tot_doc_var);
		$criteria->compare('tot_doc_muj', $this->tot_doc_muj);
		$criteria->compare('tot_doc_otr', $this->tot_doc_otr);
		$criteria->compare('tot_otr_var', $this->tot_otr_var);
		$criteria->compare('tot_otr_muj', $this->tot_otr_muj);
		$criteria->compare('dom_act', $this->dom_act, true);
		$criteria->compare('telefono', $this->telefono, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('lugar_fecha', $this->lugar_fecha, true);
		$criteria->compare('secretario', $this->secretario, true);
		$criteria->compare('vicedirector', $this->vicedirector, true);
		$criteria->compare('director', $this->director, true);
		$criteria->compare('fec_ini_act', $this->fec_ini_act, true);
		$criteria->compare('fec_ina', $this->fec_ina, true);
		$criteria->compare('fec_ani', $this->fec_ani, true);
		$criteria->compare('tot_pol_tar', $this->tot_pol_tar);
		$criteria->compare('tot_fun_tar', $this->tot_fun_tar);
		$criteria->compare('tot_ins_tar', $this->tot_ins_tar);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}